---

- name: Include Tasks by Os family
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Include vars by os Family
  include_vars: "{{ ansible_os_family }}.yml"

- name: include package manager specific vars
  with_first_found:
    - '../vars/pkg-mgr/{{ ansible_pkg_mgr }}.yml'
    - ../vars/pkg-mgr/default.yml
  include_vars: '{{ item }}'