---
    - name: print interfaces
      command: echo "{{ ansible_interfaces }}"

     # show all the hosts in the inventory
    - name: show all the hosts in the inventory
      debug:
        msg: "{{ item }}"
      loop: "{{ query('inventory_hostnames', 'all') }}"
     
     # show all the hosts in the current play
    - name: show all the hosts in the current play
      debug:
        msg: "{{ item }}"
      loop: "{{ query('changed') }}"