---
imarket_httpd_proxy_role_executed: false
- name: Include Tasks by 
  ansible.builtin.include_tasks: "{{  }}.yml"

- name: Include vars by 
  ansible.builtin.include_vars: "{{  }}.yml"

- name: include package manager specific vars
  ansible.builtin.with_first_found:
    - '../vars/pkg-mgr/{{ ansible_pkg_mgr }}.yml'
    - ../vars/pkg-mgr/default.yml
  ansible.builtin.include_vars: '{{ item }}'