---
# use for deamon reload only
- name: systemd reload
  command: systemctl daemon-reload
  tags:
  - skip_ansible_lint # [ANSIBLE0006] systemctl used in place of systemd module

# use for restart a service
- name: "restart service"
  systemd:
    name: "{{ item.key }}.service"
    state: restarted
    daemon_reload: yes
  with_dict: "{{ systemd_service }}"
  when: systemd_restart_disabled | default(True)