---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos:7
  - name: centos8
    image: centos:8
  - name: debian-stretch
    image: debian:stretch
  - name: debian-Buster
    image: debian:Buster
  - name: ubuntu-xenial
    image: ubuntu:xenial
  - name: ubuntu-Disco
    image: ubuntu:Disco
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - create
    - converge
    - destroy

verifier:
  name: test
  lint:
    name: flake8
