- debug:
    msg: "distribution-version: {{ ansible_distribution }}-{{ ansible_distribution_major_version }}"
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_debugger.html 

# On a task

- name: Execute a command
  command: false
  debugger: on_failed

On a play

- name: Play
  hosts: all
  debugger: on_skipped
  tasks:
    - name: Execute a command
      command: true
      when: False

# When provided at a generic level and a more specific level, the more specific wins:

- name: Play
  hosts: all
  debugger: never
  tasks:
    - name: Execute a command
      command: false
      debugger: on_failed

# Get mesg from project_id
- debug:
    msg: "project_id: {{ project_id }}"

# https://github.com/jongillies/rancher
# "docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v{{ rancher_agent_version }} {{ rancher_token.json['registrationUrl'] }}"
- debug:
    msg: "{{ rancher_token.json['registrationUrl'] }}"
