- debug:
    msg: "distribution-version: {{ ansible_distribution }}-{{ ansible_distribution_major_version }}"
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_debugger.html 

- name: "loop through list"
  debug:
    msg: "An item: {{item}}"
  with_items:
    - 1
    - 2
    - 3

- name: "loop through list from a variable"
  debug: 
    msg: "An item: {{item}}"
  with_items: "{{ somelist }}"

# On a task

- name: Execute a command
  command: false
  debugger: on_failed

On a play

- name: Play
  hosts: all
  debugger: on_skipped
  tasks:
    - name: Execute a command
      command: true
      when: False

# When provided at a generic level and a more specific level, the more specific wins:

- name: Play
  hosts: all
  debugger: never
  tasks:
    - name: Execute a command
      command: false
      debugger: on_failed

#
# show all the hosts in the inventory
- name: show all the hosts in the inventory
  debug:
    msg: "{{ item }}"
  loop: "{{ query('inventory_hostnames', 'all') }}"
     
# show all the hosts in the current play
- name: show all the hosts in the current play
  debug:
    msg: "{{ item }}"
  loop: "{{ query('changed') }}"
